export interface Country {
  name: string;
  nameAr: string;
  code: string; // ISO 3166-1 alpha-2
  dial: string; // e.g. "+1"
  flag: string; // emoji
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", nameAr: "أفغانستان", code: "AF", dial: "+93", flag: "🇦🇫" },
  { name: "Albania", nameAr: "ألبانيا", code: "AL", dial: "+355", flag: "🇦🇱" },
  { name: "Algeria", nameAr: "الجزائر", code: "DZ", dial: "+213", flag: "🇩🇿" },
  { name: "Andorra", nameAr: "أندورا", code: "AD", dial: "+376", flag: "🇦🇩" },
  { name: "Angola", nameAr: "أنغولا", code: "AO", dial: "+244", flag: "🇦🇴" },
  { name: "Argentina", nameAr: "الأرجنتين", code: "AR", dial: "+54", flag: "🇦🇷" },
  { name: "Armenia", nameAr: "أرمينيا", code: "AM", dial: "+374", flag: "🇦🇲" },
  { name: "Australia", nameAr: "أستراليا", code: "AU", dial: "+61", flag: "🇦🇺" },
  { name: "Austria", nameAr: "النمسا", code: "AT", dial: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", nameAr: "أذربيجان", code: "AZ", dial: "+994", flag: "🇦🇿" },
  { name: "Bahrain", nameAr: "البحرين", code: "BH", dial: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", nameAr: "بنغلاديش", code: "BD", dial: "+880", flag: "🇧🇩" },
  { name: "Belarus", nameAr: "بيلاروسيا", code: "BY", dial: "+375", flag: "🇧🇾" },
  { name: "Belgium", nameAr: "بلجيكا", code: "BE", dial: "+32", flag: "🇧🇪" },
  { name: "Bolivia", nameAr: "بوليفيا", code: "BO", dial: "+591", flag: "🇧🇴" },
  { name: "Bosnia", nameAr: "البوسنة", code: "BA", dial: "+387", flag: "🇧🇦" },
  { name: "Brazil", nameAr: "البرازيل", code: "BR", dial: "+55", flag: "🇧🇷" },
  { name: "Bulgaria", nameAr: "بلغاريا", code: "BG", dial: "+359", flag: "🇧🇬" },
  { name: "Cambodia", nameAr: "كمبوديا", code: "KH", dial: "+855", flag: "🇰🇭" },
  { name: "Cameroon", nameAr: "الكاميرون", code: "CM", dial: "+237", flag: "🇨🇲" },
  { name: "Canada", nameAr: "كندا", code: "CA", dial: "+1", flag: "🇨🇦" },
  { name: "Chile", nameAr: "تشيلي", code: "CL", dial: "+56", flag: "🇨🇱" },
  { name: "China", nameAr: "الصين", code: "CN", dial: "+86", flag: "🇨🇳" },
  { name: "Colombia", nameAr: "كولومبيا", code: "CO", dial: "+57", flag: "🇨🇴" },
  { name: "Croatia", nameAr: "كرواتيا", code: "HR", dial: "+385", flag: "🇭🇷" },
  { name: "Cuba", nameAr: "كوبا", code: "CU", dial: "+53", flag: "🇨🇺" },
  { name: "Cyprus", nameAr: "قبرص", code: "CY", dial: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", nameAr: "التشيك", code: "CZ", dial: "+420", flag: "🇨🇿" },
  { name: "Denmark", nameAr: "الدنمارك", code: "DK", dial: "+45", flag: "🇩🇰" },
  { name: "Ecuador", nameAr: "الإكوادور", code: "EC", dial: "+593", flag: "🇪🇨" },
  { name: "Egypt", nameAr: "مصر", code: "EG", dial: "+20", flag: "🇪🇬" },
  { name: "Estonia", nameAr: "إستونيا", code: "EE", dial: "+372", flag: "🇪🇪" },
  { name: "Ethiopia", nameAr: "إثيوبيا", code: "ET", dial: "+251", flag: "🇪🇹" },
  { name: "Finland", nameAr: "فنلندا", code: "FI", dial: "+358", flag: "🇫🇮" },
  { name: "France", nameAr: "فرنسا", code: "FR", dial: "+33", flag: "🇫🇷" },
  { name: "Georgia", nameAr: "جورجيا", code: "GE", dial: "+995", flag: "🇬🇪" },
  { name: "Germany", nameAr: "ألمانيا", code: "DE", dial: "+49", flag: "🇩🇪" },
  { name: "Ghana", nameAr: "غانا", code: "GH", dial: "+233", flag: "🇬🇭" },
  { name: "Greece", nameAr: "اليونان", code: "GR", dial: "+30", flag: "🇬🇷" },
  { name: "Guatemala", nameAr: "غواتيمالا", code: "GT", dial: "+502", flag: "🇬🇹" },
  { name: "Hong Kong", nameAr: "هونغ كونغ", code: "HK", dial: "+852", flag: "🇭🇰" },
  { name: "Hungary", nameAr: "المجر", code: "HU", dial: "+36", flag: "🇭🇺" },
  { name: "India", nameAr: "الهند", code: "IN", dial: "+91", flag: "🇮🇳" },
  { name: "Indonesia", nameAr: "إندونيسيا", code: "ID", dial: "+62", flag: "🇮🇩" },
  { name: "Iran", nameAr: "إيران", code: "IR", dial: "+98", flag: "🇮🇷" },
  { name: "Iraq", nameAr: "العراق", code: "IQ", dial: "+964", flag: "🇮🇶" },
  { name: "Ireland", nameAr: "أيرلندا", code: "IE", dial: "+353", flag: "🇮🇪" },
  { name: "Israel", nameAr: "إسرائيل", code: "IL", dial: "+972", flag: "🇮🇱" },
  { name: "Italy", nameAr: "إيطاليا", code: "IT", dial: "+39", flag: "🇮🇹" },
  { name: "Japan", nameAr: "اليابان", code: "JP", dial: "+81", flag: "🇯🇵" },
  { name: "Jordan", nameAr: "الأردن", code: "JO", dial: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", nameAr: "كازاخستان", code: "KZ", dial: "+7", flag: "🇰🇿" },
  { name: "Kenya", nameAr: "كينيا", code: "KE", dial: "+254", flag: "🇰🇪" },
  { name: "Kuwait", nameAr: "الكويت", code: "KW", dial: "+965", flag: "🇰🇼" },
  { name: "Latvia", nameAr: "لاتفيا", code: "LV", dial: "+371", flag: "🇱🇻" },
  { name: "Lebanon", nameAr: "لبنان", code: "LB", dial: "+961", flag: "🇱🇧" },
  { name: "Libya", nameAr: "ليبيا", code: "LY", dial: "+218", flag: "🇱🇾" },
  { name: "Lithuania", nameAr: "ليتوانيا", code: "LT", dial: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", nameAr: "لوكسمبورغ", code: "LU", dial: "+352", flag: "🇱🇺" },
  { name: "Malaysia", nameAr: "ماليزيا", code: "MY", dial: "+60", flag: "🇲🇾" },
  { name: "Maldives", nameAr: "المالديف", code: "MV", dial: "+960", flag: "🇲🇻" },
  { name: "Malta", nameAr: "مالطا", code: "MT", dial: "+356", flag: "🇲🇹" },
  { name: "Mauritania", nameAr: "موريتانيا", code: "MR", dial: "+222", flag: "🇲🇷" },
  { name: "Mexico", nameAr: "المكسيك", code: "MX", dial: "+52", flag: "🇲🇽" },
  { name: "Moldova", nameAr: "مولدوفا", code: "MD", dial: "+373", flag: "🇲🇩" },
  { name: "Monaco", nameAr: "موناكو", code: "MC", dial: "+377", flag: "🇲🇨" },
  { name: "Mongolia", nameAr: "منغوليا", code: "MN", dial: "+976", flag: "🇲🇳" },
  { name: "Morocco", nameAr: "المغرب", code: "MA", dial: "+212", flag: "🇲🇦" },
  { name: "Mozambique", nameAr: "موزمبيق", code: "MZ", dial: "+258", flag: "🇲🇿" },
  { name: "Myanmar", nameAr: "ميانمار", code: "MM", dial: "+95", flag: "🇲🇲" },
  { name: "Nepal", nameAr: "نيبال", code: "NP", dial: "+977", flag: "🇳🇵" },
  { name: "Netherlands", nameAr: "هولندا", code: "NL", dial: "+31", flag: "🇳🇱" },
  { name: "New Zealand", nameAr: "نيوزيلندا", code: "NZ", dial: "+64", flag: "🇳🇿" },
  { name: "Nigeria", nameAr: "نيجيريا", code: "NG", dial: "+234", flag: "🇳🇬" },
  { name: "North Korea", nameAr: "كوريا الشمالية", code: "KP", dial: "+850", flag: "🇰🇵" },
  { name: "Norway", nameAr: "النرويج", code: "NO", dial: "+47", flag: "🇳🇴" },
  { name: "Oman", nameAr: "عُمان", code: "OM", dial: "+968", flag: "🇴🇲" },
  { name: "Pakistan", nameAr: "باكستان", code: "PK", dial: "+92", flag: "🇵🇰" },
  { name: "Palestine", nameAr: "فلسطين", code: "PS", dial: "+970", flag: "🇵🇸" },
  { name: "Panama", nameAr: "بنما", code: "PA", dial: "+507", flag: "🇵🇦" },
  { name: "Peru", nameAr: "بيرو", code: "PE", dial: "+51", flag: "🇵🇪" },
  { name: "Philippines", nameAr: "الفلبين", code: "PH", dial: "+63", flag: "🇵🇭" },
  { name: "Poland", nameAr: "بولندا", code: "PL", dial: "+48", flag: "🇵🇱" },
  { name: "Portugal", nameAr: "البرتغال", code: "PT", dial: "+351", flag: "🇵🇹" },
  { name: "Qatar", nameAr: "قطر", code: "QA", dial: "+974", flag: "🇶🇦" },
  { name: "Romania", nameAr: "رومانيا", code: "RO", dial: "+40", flag: "🇷🇴" },
  { name: "Russia", nameAr: "روسيا", code: "RU", dial: "+7", flag: "🇷🇺" },
  { name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", code: "SA", dial: "+966", flag: "🇸🇦" },
  { name: "Senegal", nameAr: "السنغال", code: "SN", dial: "+221", flag: "🇸🇳" },
  { name: "Serbia", nameAr: "صربيا", code: "RS", dial: "+381", flag: "🇷🇸" },
  { name: "Singapore", nameAr: "سنغافورة", code: "SG", dial: "+65", flag: "🇸🇬" },
  { name: "Slovakia", nameAr: "سلوفاكيا", code: "SK", dial: "+421", flag: "🇸🇰" },
  { name: "Somalia", nameAr: "الصومال", code: "SO", dial: "+252", flag: "🇸🇴" },
  { name: "South Africa", nameAr: "جنوب أفريقيا", code: "ZA", dial: "+27", flag: "🇿🇦" },
  { name: "South Korea", nameAr: "كوريا الجنوبية", code: "KR", dial: "+82", flag: "🇰🇷" },
  { name: "Spain", nameAr: "إسبانيا", code: "ES", dial: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", nameAr: "سريلانكا", code: "LK", dial: "+94", flag: "🇱🇰" },
  { name: "Sudan", nameAr: "السودان", code: "SD", dial: "+249", flag: "🇸🇩" },
  { name: "Sweden", nameAr: "السويد", code: "SE", dial: "+46", flag: "🇸🇪" },
  { name: "Switzerland", nameAr: "سويسرا", code: "CH", dial: "+41", flag: "🇨🇭" },
  { name: "Syria", nameAr: "سوريا", code: "SY", dial: "+963", flag: "🇸🇾" },
  { name: "Taiwan", nameAr: "تايوان", code: "TW", dial: "+886", flag: "🇹🇼" },
  { name: "Tanzania", nameAr: "تنزانيا", code: "TZ", dial: "+255", flag: "🇹🇿" },
  { name: "Thailand", nameAr: "تايلاند", code: "TH", dial: "+66", flag: "🇹🇭" },
  { name: "Tunisia", nameAr: "تونس", code: "TN", dial: "+216", flag: "🇹🇳" },
  { name: "Turkey", nameAr: "تركيا", code: "TR", dial: "+90", flag: "🇹🇷" },
  { name: "UAE", nameAr: "الإمارات العربية المتحدة", code: "AE", dial: "+971", flag: "🇦🇪" },
  { name: "Uganda", nameAr: "أوغندا", code: "UG", dial: "+256", flag: "🇺🇬" },
  { name: "Ukraine", nameAr: "أوكرانيا", code: "UA", dial: "+380", flag: "🇺🇦" },
  { name: "United Kingdom", nameAr: "المملكة المتحدة", code: "GB", dial: "+44", flag: "🇬🇧" },
  { name: "USA", nameAr: "الولايات المتحدة", code: "US", dial: "+1", flag: "🇺🇸" },
  { name: "Uruguay", nameAr: "أوروغواي", code: "UY", dial: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", nameAr: "أوزبكستان", code: "UZ", dial: "+998", flag: "🇺🇿" },
  { name: "Venezuela", nameAr: "فنزويلا", code: "VE", dial: "+58", flag: "🇻🇪" },
  { name: "Vietnam", nameAr: "فيتنام", code: "VN", dial: "+84", flag: "🇻🇳" },
  { name: "Yemen", nameAr: "اليمن", code: "YE", dial: "+967", flag: "🇾🇪" },
  { name: "Zimbabwe", nameAr: "زيمبابوي", code: "ZW", dial: "+263", flag: "🇿🇼" }
];
